# 提高 Gradle 可用内存
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA 与配置缓存尚未完全兼容
org.gradle.configuration-cache=false

# Fabric 属性
# 版本请以 https://fabricmc.net/develop 为准
minecraft_version=1.21.8
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod 属性
version=1.0.1
group=net.chatblocker

# 依赖版本
fabric_api_version=0.136.1+1.21.8
modmenu_version=15.0.2
yacl_version=3.8.2+1.21.6-fabric
